[tool.black]
line-length = 100
target-version = ["py311"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | build
  | dist
  | htmlcov
  | doc
)/
'''

[tool.coverage.run]
omit = [
    "*/tests/*",
    "pig_game/ai_game.py"
]

[tool.coverage.report]
fail_under = 85
