name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -V
          pip list

      - name: Lint (flake8 isolated)
        run: |
          echo "Running flake8 (isolated)…"
          flake8 --isolated \
                 --max-line-length 100 \
                 --extend-ignore D203,D213 \
                 --exclude .git,__pycache__,venv,.venv,build,dist,doc/api,htmlcov \
                 .

      - name: Lint docstrings (pydocstyle)
        run: |
          echo "Running pydocstyle (google)…"
          pydocstyle --convention=google --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107 pig_game

      - name: Lint (pylint errors only)
        run: |
          echo "Running pylint -E…"
          pylint -E pig_game

      - name: Run tests
        run: |
          echo "Running pytest with coverage…"
          coverage run -m pytest -q || true
          echo "Pytest exit code was $?"

      - name: Coverage report + HTML
        run: |
          coverage report -m || true
          coverage html || true

      - name: Upload coverage HTML artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov
