name: CI
on:
  push:
    branches: [ main, Mohammed ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          python -V
          pip list

      - name: flake8 (non-blocking)
        continue-on-error: true
        run: |
          mkdir -p ci-logs
          flake8 --isolated --max-line-length 120 \
                 --extend-ignore D100,D101,D102,D103,D104,D105,D106,D107,D204,D205,E302,E305,E501 \
                 --exclude .git,__pycache__,venv,.venv,build,dist,doc/api,htmlcov \
                 . | tee ci-logs/flake8.txt

      - name: pydocstyle (non-blocking)
        continue-on-error: true
        run: |
          pydocstyle --convention=google \
                     --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107 pig_game \
                     | tee ci-logs/pydocstyle.txt

      - name: pylint -E (non-blocking)
        continue-on-error: true
        run: |
          pylint -E pig_game | tee ci-logs/pylint.txt || true

      - name: Pytest + coverage (non-blocking)
        continue-on-error: true
        run: |
          coverage run -m pytest -q || true
          coverage report -m || true
          coverage html || true

      - name: Upload coverage html
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov

      - name: Upload lint logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-logs
          path: ci-logs
